### ISSUE TITLE
Enhancement: Remove cyclic dependencies.

### ISSUE THREAD

**Issue by janiversen** [home-assistant-libs/pytradfri#381]
The library currently is messy in its imports:

e.g. device.py import blind_control, blind_control import blind, blind import device, causing a cyclic import.

We whould restructure a bit so that:
- api only imports errors/const
- device only import api/errrors/const
- pytradfri imports as needed

Secondly device should be cleaned up, so that device becomes a base class.
Currently each device type (e.g. blinds) have a variable _device, that is the device, it would be cleaner if we did not create device and distribute it, but instead created the correct type directly.

Such a change will in the longer term allow us to hide APIFactory in device, and thus make allows library users to work directly with  the device types.

I would like to have feedback on the idea, since it is a rather big change.

**Comment by MartinHjelmare** [comment]
There are no cyclic imports during runtime. `blind` only imports from `device` for type hints. That's fine. The api is isolated today since the library has a sans-io foundation. None of the other modules import the api.

I don't see the immediate benefit of using an inheritance approach over the current composition approach. Is there an interface that is not clearly defined in the device data implementations (blind)?

How would we hide the APIFactory in the device while still keeping the sans-io foundation of the library? I think I'd need to see an example to better understand.

**Comment by janiversen** [comment]
The type hints just make the problem clearer, the problem very well exist independently. blind.py uses device as a parameter even though device.py is not initialized etc.

It is true that the current calling sequences works and bypassed the conflicts, but I have hid several “interesting” problems when working on the code and it is just a matter of time before we hit it in the production code.

The APIFactory within device, would mean that users of the library would not do “api(request)” to turn on the lights but would instead do “light.turnon()”. That way users of the library do not need to know how “turnon()” communicates with the IKEA hub. Each device type (or more correctly the base class) would implement the observe command again making the outside usage simpler.

Using HA integration tradfri as an example, the exterior code would be a lot simpler, including timeout monitoring etc.

Of course such a change would be a break from the current API, and would surely be a version 8.0.0, allowing users that do no want to change to stay on 7.x

**Comment by MartinHjelmare** [comment]
The device package is imported before eg blind is executed since the blind module is part of the device package. I'm not following your statement about initialization.

Users don't currently need to know how the device communicates with the api. The api abstracts that.

You haven't answered my question about the library design being sans-io based. Are you saying we should remove that principle?

**Comment by MartinHjelmare** [comment]
I think it's mostly the observation interface that may leak some details out of the api. Maybe we just need to improve on that?

**Comment by janiversen** [comment]
No I do not think we should remove that principle, but in reality the current design is not truly sans-io based, because the users of library need to care about e.g. network time and (as you just wrote) observe with starting of tasks.

I am not sure what the name is (when not sans-io), but I would like to have an abstraction layer, so the users see light, blind etc…and not api(request).

**Comment by MartinHjelmare** [comment]
I think it would be ok to re-work the user interface if we still keep the foundation and its pieces intact. Maybe we can even do it backwards compatible?

I think you should make a proof of concept before we decide so it's easier to see and discuss.

**Comment by janiversen** [comment]
Making proof of concept would be easier if I could make feature branches….but I suppose I have to do in my private repo.
